variable "namespace" {
  description = "Prefix for all resources generated by the pipeline"
  type        = string
}

variable "vpc_id" {
  description = "VPC ID to build in"
  type        = string
}

variable "environment" {
  description = "Name of the AWS deployment environment"
  type        = string
}

variable "island_subnet_a" {
  description = "Subnets used for Service Template"
  type        = string
}

variable "island_subnet_b" {
  description = "Subnets used for Service Template"
  type        = string
}

variable "routable_subnet_a" {
  description = "Subnets used for Service Template"
  type        = string
}

variable "routable_subnet_b" {
  description = "Subnets used for Service Template"
  type        = string
}

variable "ecs_cluster" {
  description = "Cluster used to create and execute tasks"
  type        = string
}

variable "image" {
  description = "The container to run tasks in"
  type        = string
}

variable "tag" {
  description = "Used as the aws log stream prefix"
  type        = string
}

variable "runner_group" {
  description = "Name of the runner group"
  type        = string
  default     = null
}

variable "runner_labels" {
  description = "Comma-separated list of runner labels"
  type        = string
  default     = null
}

variable "github_pat" {
  type        = string
  description = "github personal access token"
  sensitive   = true
}

variable "github_url" {
  type        = string
  description = "github url"
  default     = "https://github.com/api/v3"
}

variable "github_org" {
  type        = string
  description = "github organization"
}

variable "github_repo" {
  type        = string
  description = "github repository"
}

variable "webhook_events" {
  type        = list(string)
  description = "github webhook events"
}
